"""Add primary_image_url to activities

Revision ID: 0fae3bf84f7e
Revises: 001
Create Date: 2025-07-13 09:52:44.304044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0fae3bf84f7e"
down_revision = "001"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_activities_activity_date", table_name="activities")
    op.drop_index("ix_activities_id", table_name="activities")
    op.drop_index("ix_activities_trip_id", table_name="activities")
    op.drop_table("activities")
    op.add_column(
        "activitys",
        sa.Column("primary_image_url", sa.String(length=1000), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("activitys", "primary_image_url")
    op.create_table(
        "activities",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("name", sa.VARCHAR(length=200), nullable=False),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("trip_id", sa.INTEGER(), nullable=False),
        sa.Column("activity_date", sa.DATE(), nullable=False),
        sa.Column("time_slot", sa.VARCHAR(length=9), nullable=False),
        sa.Column("category", sa.VARCHAR(length=14), nullable=False),
        sa.Column("priority", sa.VARCHAR(length=10), nullable=False),
        sa.Column("location_name", sa.VARCHAR(length=200), nullable=True),
        sa.Column("address", sa.TEXT(), nullable=True),
        sa.Column("latitude", sa.FLOAT(), nullable=True),
        sa.Column("longitude", sa.FLOAT(), nullable=True),
        sa.Column("estimated_cost", sa.FLOAT(), nullable=False),
        sa.Column("actual_cost", sa.FLOAT(), nullable=True),
        sa.Column("notes", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("updated_at", sa.DATETIME(), nullable=False),
        sa.ForeignKeyConstraint(
            ["trip_id"],
            ["trips.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_activities_trip_id", "activities", ["trip_id"], unique=False)
    op.create_index("ix_activities_id", "activities", ["id"], unique=False)
    op.create_index(
        "ix_activities_activity_date", "activities", ["activity_date"], unique=False
    )
    # ### end Alembic commands ###
