"""Add Chinese content fields to Activity table

Revision ID: 114cc113bbfb
Revises: 8d6d9b1483c9
Create Date: 2025-07-13 18:44:21.687399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114cc113bbfb'
down_revision = '8d6d9b1483c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activitys', sa.Column('description_zh', sa.Text(), nullable=True))
    op.add_column('activitys', sa.Column('cultural_notes_zh', sa.Text(), nullable=True))
    op.add_column('activitys', sa.Column('tips_for_chinese_travelers', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activitys', 'tips_for_chinese_travelers')
    op.drop_column('activitys', 'cultural_notes_zh')
    op.drop_column('activitys', 'description_zh')
    # ### end Alembic commands ###