"""add_profile_image_url_to_family_members

Revision ID: 6447cfd01c6d
Revises: 0fae3bf84f7e
Create Date: 2025-07-13 10:32:16.504587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6447cfd01c6d'
down_revision = '0fae3bf84f7e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('family_members', sa.Column('profile_image_url', sa.String(length=1000), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('family_members', 'profile_image_url')
    # ### end Alembic commands ###