"""Add translation cache table

Revision ID: 8d6d9b1483c9
Revises: a51959f4b6b2
Create Date: 2025-07-13 16:01:19.514717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d6d9b1483c9'
down_revision = 'a51959f4b6b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('translation_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_text_hash', sa.String(length=64), nullable=False),
    sa.Column('source_language', sa.String(length=5), nullable=False),
    sa.Column('target_language', sa.String(length=5), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('translation_service', sa.String(length=50), nullable=True),
    sa.Column('translation_model', sa.String(length=50), nullable=True),
    sa.Column('translation_quality_score', sa.Integer(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_translation_cache_id'), 'translation_cache', ['id'], unique=False)
    op.create_index(op.f('ix_translation_cache_source_text_hash'), 'translation_cache', ['source_text_hash'], unique=False)
    op.create_index('ix_translation_lookup', 'translation_cache', ['source_text_hash', 'source_language', 'target_language'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_translation_lookup', table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_source_text_hash'), table_name='translation_cache')
    op.drop_index(op.f('ix_translation_cache_id'), table_name='translation_cache')
    op.drop_table('translation_cache')
    # ### end Alembic commands ###