"""Add Chinese content fields and translation cache

Revision ID: a51959f4b6b2
Revises: 6447cfd01c6d
Create Date: 2025-07-13 16:00:42.542475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a51959f4b6b2'
down_revision = '6447cfd01c6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_recommendations', sa.Column('description_zh', sa.Text(), nullable=True))
    op.add_column('activity_recommendations', sa.Column('cultural_notes_zh', sa.Text(), nullable=True))
    op.add_column('activity_recommendations', sa.Column('tips_for_chinese_travelers', sa.Text(), nullable=True))
    op.add_column('activity_recommendations', sa.Column('quality_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_recommendations', 'quality_score')
    op.drop_column('activity_recommendations', 'tips_for_chinese_travelers')
    op.drop_column('activity_recommendations', 'cultural_notes_zh')
    op.drop_column('activity_recommendations', 'description_zh')
    # ### end Alembic commands ###