"""add_chinese_content_fields_to_activity_table

Revision ID: b4c64a95b055
Revises: 114cc113bbfb
Create Date: 2025-07-13 20:20:44.201773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4c64a95b055'
down_revision = '114cc113bbfb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###